// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

int index =0;

void ButtonClicked(lv_event_t * e)
{
	index++;

	if(index == 1)
		lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(0x003a57), LV_PART_MAIN);
	else if(index == 2)
		lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(0x00FF57), LV_PART_MAIN);
	else if(index == 3)
		lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(0x0FF057), LV_PART_MAIN);
	else if(index == 4)
		lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(0xFF0000), LV_PART_MAIN);
	else
	{
		lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(0xFF0450), LV_PART_MAIN);
		index =0;
	}
}
