// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: GUI_prj1

#include "ui.h"

typedef enum {
    MODE_NONE,
    MODE_RED,
    MODE_GREEN
} color_mode_t;

static color_mode_t active_mode = MODE_NONE; // Tracks last pressed button

void RedButton(lv_event_t * e)
{
    lv_obj_t * scr = lv_scr_act();
    lv_obj_set_style_bg_color(scr, lv_color_make(255, 0, 0), 0); // Full red
    active_mode = MODE_RED;
}

void GreenButton(lv_event_t * e)
{
    lv_obj_t * scr = lv_scr_act();
    lv_obj_set_style_bg_color(scr, lv_color_make(0, 255, 0), 0); // Full green
    active_mode = MODE_GREEN;
}

void SliderFunc(lv_event_t * e)
{
    if (active_mode == MODE_NONE) return; // No color selected yet

    lv_obj_t * slider = lv_event_get_target(e);
    int val = lv_slider_get_value(slider); // Slider value (0–100)

    // Map slider value to brightness (0–255)
    uint8_t level = (val * 255) / 100;

    lv_obj_t * scr = lv_scr_act();

    if (active_mode == MODE_GREEN)
        lv_obj_set_style_bg_color(scr, lv_color_make(0, level, 0), 0);
    else if (active_mode == MODE_RED)
        lv_obj_set_style_bg_color(scr, lv_color_make(level, 0, 0), 0);
}